version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: atronautas

  nest-app:
    build: .
    container_name: nest-app
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/atronautas
    command: npm run start:dev

volumes:
  mongo-data:
